# Generated by Django 3.0.5 on 2020-04-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.CharField(choices=[('Poor', 'Poor'), ('Average', 'Average'), ('Satisfactory', 'Satisfactory'), ('Good', 'Good'), ('Excellent', 'Excellent')], max_length=20)),
                ('text', models.TextField()),
            ],
        ),
    ]
