# Generated by Django 3.0.5 on 2020-04-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200422_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.jpeg', height_field='profile_image_height', null=True, upload_to='user_profile_images/%Y/%m/%d/', width_field='profile_image_width'),
        ),
    ]
