# Generated by Django 3.0.5 on 2020-04-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20200422_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentChatRooms',
            fields=[
                ('sockets_channel_name', models.TextField(primary_key=True, serialize=False)),
                ('chat_room_name', models.TextField()),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='thread',
            name='visible_for_first',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='visible_for_second',
            field=models.BooleanField(default=True),
        ),
    ]
