# Generated by Django 3.0.5 on 2020-04-23 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20200424_0057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentChatRooms',
        ),
    ]
