# Generated by Django 3.0.5 on 2020-04-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_delete_currentchatrooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentChatRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sockets_channel_name', models.TextField()),
                ('user', models.CharField(max_length=151)),
                ('chat_room_name', models.TextField()),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
